from pydantic import BaseModel, Field
from typing import Optional, Any, Dict, List


class PersonalContextRequest(BaseModel):
    content: str


class PersonalContextResponse(BaseModel):
    status: str


class RealtimeRequest(BaseModel):
    context: Optional[str] = None
    voice: Optional[str] = None


class RealtimeResponse(BaseModel):
    client_secret: str


class WhisperRequest(BaseModel):
    text: str
    voice_description: Optional[str] = None


# --- Enrichment Endpoint Models ----------------------------------------------------


class EnrichLinkedInRequest(BaseModel):
    url: str


class EnrichLinkedInResponse(BaseModel):
    input_url: str
    person: Optional[Dict[str, Any]] = None
    company: Optional[Dict[str, Any]] = None
    search_results: Optional[List[Dict[str, Any]]] = Field(
        None, description="Brave search results from ACI.dev if a company was found."
    )
    autofill_context: str = Field(
        ...,
        description="Bulleted list of key insights for MOM Test prep, generated by AI.",
    )


# --- Background Session (non-Realtime) -------------------------------------------


class StartSessionRequest(BaseModel):
    context: Optional[str] = None
    speak_hints: Optional[bool] = False


class StartSessionResponse(BaseModel):
    session_id: str


class HintItem(BaseModel):
    hint: str
    followup_question: str


class HintsResponse(BaseModel):
    hints: List[HintItem]


class EndSessionResponse(BaseModel):
    ok: bool
    removed: bool


# --- Aspect Suggestion ------------------------------------------------------------

class AspectSuggestRequest(BaseModel):
    session_id: str
    aspect: str  # one of: compliment, hypothetical, leading, pitching, fluff, yesno, vague


class AspectSuggestResponse(BaseModel):
    question: str


class AspectDetectRequest(BaseModel):
    session_id: str
    text: str


class AspectDetectResponse(BaseModel):
    aspects: List[str]


# --- LLM Aspect Detection ---------------------------------------------------------

class AspectDetectRequest(BaseModel):
    session_id: str
    text: str


class AspectDetectResponse(BaseModel):
    aspects: List[str]
